<?php
$product = $block->getProduct();
if ($product && !$block->isProductAvailable()): ?>
    <div class="notify-me-form">
        <form action="<?php echo $block->getUrl('notifyme/index/post') ?>" method="post">
            <input type="hidden" name="product_id" value="<?php echo $block->escapeHtml($product->getId()) ?>" />
            <div class="field">
                <label for="email"><?php echo __('Enter your email to be notified when this product is back in stock:') ?></label>
                <input type="email" name="email" id="email" required="required" />
            </div>
            <div class="actions">
                <button type="submit"><?php echo __('Notify Me') ?></button>
            </div>
        </form>
    </div>
<?php endif; ?>
<p>Hello</p>


<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "Magento_Customer/js/block-submit-on-send": {-->
<!--                "formId": "contact-form"-->
<!--            }-->
<!--        }-->
<!--    }-->
<!--</script>-->
